MODEL:
  NAME: pruned_vit
  TYPE: pruned_vit

TRAIN:
  EPOCHS: 1

DATA:
  IMG_SIZE: 1024
  MEAN_AND_STD_TYPE: default
  DATASET: sa1b
  DATA_PATH: datasets/substation_equipment

DISTILL:
  EMBED_DIM: 256
  SAVE_TEACHER_EMBED: True
  TEACHER_EMBED_PATH: teacher_embed/substation_equipment_slimsam50se