MODEL:
  TYPE: rep_vit_m1
  PRETRAINED: output_substation_equipment/rep_vit_m1_fuse_substation_equipment_distill_100e/default/ckpt_epoch_99.pth

TRAIN:
  EPOCHS: 50
  BASE_LR: 3.2e-3
  MIN_LR: 3.2e-4
  WARMUP_LR: 3.2e-5
  WARMUP_EPOCHS: 0
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 0.01
SAVE_FREQ: 10

DATA:
  IMG_SIZE: 1024
  MEAN_AND_STD_TYPE: default
  DATASET: sa1b
  DATA_PATH: datasets/substation_equipment/
  NUM_WORKERS: 4
  BATCH_SIZE: 4

DISTILL:
  EMBED_DIM: 256
  TEACHER_EMBED_PATH: teacher_embed/substation_equipment_slimsam50se_240927/
  NO_RAND: True
  FUSE: True
  ENCODER_ONLY: False
  DECODER_BCE: 5.0
  DECODER_DICE: 5.0
  MAX_ALLOWED_PROMPTS: 16
  PROMPT_TYPE: ['box']
  DECODE_ITERS: 2
  POINTS_PER_REFINE_ITER: 1
  ITER_ON_BOX: True
  MULTIMASK_OUTPUT: 4

AMP_ENABLE: False